create table salary (
    id bigint generated by default as identity,
    year_eight integer not null,
    year_five integer not null,
    year_four integer not null,
    year_nine integer not null,
    year_one integer not null,
    year_seven integer not null,
    year_six integer not null,
    year_ten integer not null,
    year_three integer not null,
    year_two integer not null,
    primary key (id)
);